name: Run linter

on:
  push:
    branches: ["main", "feat/*"]
  pull_request:
    branches: ["main", "feat/*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20.7

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.2
          args: --timeout 10m0s --max-issues-per-linter 0 --max-same-issues 0 --print-issued-lines
          only-new-issues: true
